POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test blog",
  "author": "Test author",
  "url": "http://test.com",
  "likes": 0
}
###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsImlkIjoiNjU4MGU2NzgxZDc4YmJlYzQxZjdiZjJmIiwiaWF0IjoxNzA0MzA5MDIyLCJleHAiOjE3MDQzMTI2MjJ9.rNOQLheRzO95tZ_RZ0ghdFOo8x0Updet2psdskvuqrE

{
  "title": "We get it on most every night",
  "author": "When that moon is big and bright",
  "url": "http://test.com",
  "likes": 0
}
